CRMApp/Models/Note.cs
using CRMApp.Areas.Identity.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CRMApp.Models
{
    public class Note
    {
        [Key]
        public int Id { get; set; }

        public int CustomerId { get; set; }

        [Required]
        public string Description { get; set; }


        public string CreatedBy { get; set; }

        [DisplayName("Created on")]
        [DisplayFormat(DataFormatString = "{0:dd MMMM, yyyy hh:mm tt}")]
        public DateTime CreatedAt { get; set; }

        [ForeignKey(nameof(CustomerId))]
        public Customer Customer { get; set; }

        [ForeignKey(nameof(CreatedBy))]
        public ApplicationUser ApplicationUser { get; set; }

    }
}

CRMApp/ViewModels/ContactViewModel.cs
using CRMApp.Models;
using CRMApp.Services;
using System.ComponentModel.DataAnnotations;

namespace CRMApp.ViewModels
{
    public class ContactViewModel
    {
        private readonly ICustomerService _customerService;

        public ContactViewModel() { }

        public ContactViewModel(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public PaginatedList<CustomerContact>? Contacts { get; set; }
        public CustomerContact? customerContact { get; set; }

        public ContactFilter ContactFilter { get; set; }

        [Required(ErrorMessage = "Search Input should not be Empty...")]
        public string? ContactInput { get; set; }


        public string CustomerName(int customerId)
        {
            return _customerService.GetCustomer(customerId).Name;
        }
    }
}

CRMApp/Areas/Identity/Data/UserViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CRMApp.Areas.Identity.Data
{
    public class UserViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UserViewComponent(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            return View(user);
        }
    }
}

CRMApp/Controllers/ContactController.cs
using CRMApp.Models;
using CRMApp.Services;
using CRMApp.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CRMApp.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactService _contactService;
        private readonly ICustomerService _customerService;
        private readonly int PageSize = 5;

        public ContactController(IContactService contactService, ICustomerService customerService)
        {
            _contactService = contactService;
            _customerService = customerService;
        }
        public IActionResult Index(int pageIndex = 1)
        {
            if (User.IsInRole("admin"))
            {
                var result = _contactService.GetAllContacts(pageIndex);
                var contacts = result.contacts;
                var totalContacts = result.contactCount;
                var viewModel = new ContactViewModel(_customerService)
                {
                    Contacts = new PaginatedList<CustomerContact>(contacts, totalContacts, pageIndex, PageSize)
                };
                return View(viewModel);
            }
            return RedirectToAction("Index", "Dashboard");
        }

        [HttpPost]
        public IActionResult Index(ContactViewModel contactViewModel, int pageIndex)
        {
            var totalContacts = _contactService.GetContacts(contactViewModel.ContactFilter, contactViewModel.ContactInput, null).Count();
            var contacts = _contactService.GetContacts(contactViewModel.ContactFilter, contactViewModel.ContactInput, null, pageIndex);
            var viewModel = new ContactViewModel(_customerService)
            {
                Contacts = new PaginatedList<CustomerContact>(contacts, totalContacts, pageIndex, PageSize)
            };
            return View(viewModel);
        }


        [HttpPost]
        public IActionResult SaveContact(CustomerViewModel viewModel)
        {
            if (viewModel.CustomerContact != null)
            {
                _contactService.CreateContact(viewModel.CustomerContact);
                return RedirectToAction("Details", "Customer", new { Id = viewModel.CustomerContact.CustomerId });
            }

            return View(viewModel);

        }

        [HttpPost]
        public IActionResult DeleteContact(int id)
        {
            var CustId = _contactService.GetContact(id).CustomerId;
            if (!_contactService.DeleteContact(id))
            {
                return NotFound();
            }

            return RedirectToAction("Details", "Customer", new { Id = CustId });

        }

        [HttpGet]
		public IActionResult PagedData( int customerId ,int pageIndex = 1)
		{
			if (pageIndex < 1)
			{
				pageIndex = 1;
			}

            var data = _contactService.GetContacts(customerId,pageIndex);
			return PartialView("_ContactList",data);
		}

	}
}

CRMApp/Controllers/ContactInquiryController.cs
using CRMApp.Models;
using CRMApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace CRMApp.Controllers
{
    public class ContactInquiryController : Controller
    {
        private readonly IContactInquiryService _contactInquiryService;

        public ContactInquiryController(IContactInquiryService contactInquiryService)
        {
            _contactInquiryService = contactInquiryService;
        }

        public IActionResult Index()
        {
            var inquiries = _contactInquiryService.GetAllInquiries();
            return View(inquiries);
        }

        [HttpPost]
        public IActionResult SaveInquiry(ContactInquiry contactInquiry)
        {
            _contactInquiryService.SaveInquiry(contactInquiry);
            return RedirectToAction("Index", "Home");
        }


        public IActionResult ArchiveEnquiry(int id)
        {
            var inquiry = _contactInquiryService.GetInquiry(id);
            inquiry.isArchived = true;
            _contactInquiryService.SaveInquiry(inquiry);
            return RedirectToAction("Index");
        }
    }
}

CRMApp/Controllers/NoteController.cs
using CRMApp.Services;
using CRMApp.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CRMApp.Controllers
{
    public class NoteController : Controller
    {
        private readonly INoteService _noteService;

        public NoteController(INoteService noteService)
        {
            _noteService = noteService;
        }
        public IActionResult Index()
        {
            var notes = _noteService.GetAllNotes();
            return View(notes);
        }

        [HttpPost]
        public IActionResult SaveNote(CustomerViewModel viewModel)
        {
            if (viewModel.Note != null)
            {
                _noteService.SaveNote(viewModel.Note);
                return RedirectToAction("Details", "Customer", new { Id = viewModel.Note.CustomerId });
            }

            return View(viewModel);
        }


        [HttpPost]
        public IActionResult DeleteNote(int id)
        {
            var deletedNote = _noteService.GetNoteById(id);
            _noteService.DeleteNote(id);
            return RedirectToAction("Details", "Customer", new { Id = deletedNote.CustomerId });
        }


        public IActionResult PagedData(int customerId, int pageIndex)
        {
            var data = _noteService.GetNoteByCustomerId(customerId, pageIndex);

            return PartialView("_NoteList", data);
        }

    }
}

CRMApp/Views/Shared/AdminDashboard.cshtml
@model CRMApp.ViewModels.ActivityLogViewModel;
@{
	ViewData["Title"] = "AdminDashboard";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<div class="d-flex justify-content-center mt-5">
	<div class="flex-column" style="width: 100%;">
		<div class="d-grid">
			<div class="row d-flex justify-content-between ms-0">
				<div class="col-2" style="width: 59em; margin-left:-2rem;">
					<div class="card shadow-sm">
						<h3 class="text-center mt-2">Overview</h3>
						<div class="card-body">
							<div class="d-grid">
								<div class="row d-inline-flex justify-content-center gap-5">
									<div class="col-sm-3" style="width: 15rem;">
										<div class="card" style="background: lightgrey;" id="user-tile">
											<div class="card-body">
												<h4 class="text-center">Total Users </h4>
												<p class="text-center fw-bold h5">@ViewBag.UserCount</p>
											</div>
										</div>
									</div>


									<div class="col-sm-3" style="width: 15rem;">
										<div class="card" style="background: lightgrey;" id="customer-tile">
											<div class="card-body">
												<h4 class="text-center">Total Customers </h4>
												<p class="text-center fw-bold h5">@ViewBag.CustomerCount</p>
											</div>
										</div>
									</div>
									<div class="col-sm-3 me-1" style="width: 15rem;">
										<div class="card" style="background: lightgrey;" id="contact-tile">
											<div class="card-body">
												<h4 class="text-center">Total Contacts </h4>
												<p class="text-center fw-bold h5">@ViewBag.ContactCount</p>
											</div>
										</div>
									</div>

								</div>

							</div>
						</div>
					</div>
					<div class="card shadow-sm mt-4 d-flex justify-content-center">
						<h3 class="text-center mt-3 mb-3 message">Enquiries</h3>
						<div class="row gap-2 mb-3 justify-content-center">
							@foreach(var item in Model.contactInquiries){
								
								
									<div class="card col-3 Enquiry-tile" style="width: 16rem;" data-email="@item.Email" data-name="@item.Name" data-timeStamp="@item.CreatedAt" data-EnquiryMessage="@item.Message" data-bs-toggle="modal" data-bs-target="#detailModal">
										<span class="message-text mt-3"><span class="fw-bold">Name:</span> @item.Name</span>
										<span class="message-text"><span class="fw-bold">Email:</span> @item.Email</span>
										<span class="message-text mb-3"><span class="fw-bold">Date:</span> @Model.FormatDate(item.CreatedAt) at @item.CreatedAt.ToString("h:mm tt") </span>
									</div>
								
							}
						</div> 
						<a class="text-end me-4 mb-3 text-decoration-none text-dark " asp-action="Index" asp-controller="ContactInquiry">
							View all
							<i class="bi bi-arrow-right"></i>
						</a>
					</div>
				</div>
				<div class="col-2" style="width:25em;margin-right: -1rem;">
					<div class="card shadow-sm" style="overflow-y: auto; height: 650px;">
						<h3 class="text-center mt-2">
							Activity Feed
						</h3>
						@if (Model.activityLogs.Count == 0)
						{
							<p class="text-center fw-light mt-5">No Activity To Show</p>
						}
						else
						{
							@foreach (var item in Model.activityLogs)
							{

								<div class="container mt-1 mb-1">
									<div class="card shadow-sm">
										<div class="card-header d-inline-flex justify-content-between">
											<span class="fw-bold">@item.ModuleId</span>
										</div>
										<div class="card-body">
											@if ((bool)item.IsDeleted)
											{
												<span class="text-danger">@item.Action  </span>  <span class="fst-italic text-end text-danger">On @Model.FormatDate(item.TimeStamp) at @item.TimeStamp.ToString("h:mm tt")</span>
											}
											else
											{
												<span class="text-success">@item.Action </span> <span class="fst-italic text-end text-success">On @Model.FormatDate(item.TimeStamp) at @item.TimeStamp.ToString("h:mm tt")</span>
											}
										</div>

									</div>
								</div>

							}
							<nav class="d-flex justify-content-center mt-1">
								<ul class="pagination">
									@if (Model.activityLogs.HasPreviousPage)
									{
										<li class="page-item"><a class="page-link" href="?pageIndex=@(Model.activityLogs.PageIndex - 1)">Previous</a></li>
									}
									@for(int i = Model.activityLogs.StartPage; i <= Model.activityLogs.EndPage; i++)
									{
										<li class="@(i == Model.activityLogs.PageIndex ? "active" : "") page-item">
											<a href="?pageIndex=@i" class="page-link">@i</a>
										</li>
									}
									@if (Model.activityLogs.HasNextPage)
									{
										<li class="page-item">
											<a href="?pageIndex=@(Model.activityLogs.PageIndex + 1)" class="page-link">Next</a>
										</li>
									}
								</ul>
							</nav>
						}

					</div>
				</div>
			</div>
		</div>

	</div>

</div>

<div class="modal fade" tabindex="-1" id="detailModal" aria-hidden="true" style="z-index: 100000;">
	<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Enquiry Details</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<span class="fw-bold">Name: </span><span id="name"></span><br />
				<span class="fw-bold">Email: </span><span id="email"></span><br />
				<span class="fw-bold">TimeStamp: </span><span id="timeStamp"></span><br />
				<span class="fw-bold">Message: </span><span id="EnquiryMessage"></span>

			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
				
			</div>
		</div>
	</div>
</div>


@section Scripts {
	
	<script>
		$("#customer-tile").click(function () {
			window.location.href = "/Customer/Index"
		})

		$("#contact-tile").click(function() {
			window.location.href = "/Contact/Index"
		})

		$("#user-tile").click(function(){
			window.location.href = "/User/Index"
		})
		$(document).ready(function(){
			$("card").css("background-color", "#ecf0f1")
			$("#customer-tile").css("background-color","#2c3e50")
			$("#user-tile").css("background-color","#2c3e50")
			$("#contact-tile").css("background-color","#2c3e50")
			$("h4").addClass("text-light")
			$("p").addClass("text-light")
			$(".message-text").addClass("text-light")
			$(".message").removeClass("text-light")
			$(".Enquiry-tile").css("background-color", "#2c3e50")

			var myModal = $("#detailModal")

			$(".Enquiry-tile").on('click',function(){
				var name = $(this).data("name");
				var email = $(this).data("email");
				var timeStamp = $(this).data("timestamp");
				var message = $(this).data("enquirymessage");

				$('#name').text(name)
				$('#email').text(email)
				$('#timeStamp').text(timeStamp)
				$('#EnquiryMessage').text(message).css('white-space', 'pre-line')
				
				myModal.show();
			})
		})
	</script>
}

CRMApp/Views/Shared/SalesDashboard.cshtml
@model CRMApp.ViewModels.ActivityLogViewModel;

@{
	ViewData["Title"] = "SalesDashboard";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container d-flex justify-content-center ">
	<div class="flex-column" style="width: 100%;">
		
		<div class="d-grid">
			<div class="row d-flex justify-content-between ms-0">
				<div class="col-2" style="width: 58em;margin-left:-3rem">
					<div class="card">
						<h3 class="text-center mt-2">Overview</h3>
						<div class="card-body">
							<div class="d-grid">
								<div class="row d-inline-flex justify-content-center">

									<div class="col-sm-2" style="width: 15rem;">
										<div class="card"  id="customer-tile">
											<div class="card-body">
												<h4 class="text-center text-light">Total Customers </h4>
												<p class="text-center fw-bold h5 text-light">@ViewBag.CustomerCount</p>
											</div>
										</div>
									</div>
									<div class="col-sm-2" style="width: 15rem;">
										<div class="card" style="background: lightgrey;" id="contact-tile">
											<div class="card-body">
												<h4 class="text-center text-light">Total Contacts </h4>
												<p class="text-center fw-bold h5 text-light">@ViewBag.ContactCount</p>
											</div>
										</div>
									</div>

								</div>

							</div>
						</div>
					</div>
				</div>
				<div class="col-2" style="width:27em; margin-right:-2rem;">
					<div class="card shadow-sm" style="overflow-y: auto; height: 600px;">
						<h3 class="text-center mt-2">
							Activity Feed
						</h3>
						@if (Model.activityLogs == null || Model.activityLogs.Count == 0)
						{
							<p class="text-center fw-light mt-5">No Activity To Show</p>
						}
						else
						{
							@foreach (var item in Model.activityLogs)
							{

								<div class="container mt-1 mb-1">
									<div class="card">
										<div class="card-header d-inline-flex justify-content-between">
											<span class="fw-bold">@item.ModuleId</span>
										</div>
										<div class="card-body">
											@if ((bool)item.IsDeleted)
											{
												<span class="text-danger">@item.Action  </span>  <span class="fst-italic text-end text-danger">On @Model.FormatDate(item.TimeStamp) at @item.TimeStamp.ToString("h:mm tt")</span>
											}
											else
											{
												<span class="text-success">@item.Action </span> <span class="fst-italic text-end text-success">On @Model.FormatDate(item.TimeStamp) at @item.TimeStamp.ToString("h:mm tt")</span>
											}

										</div>

									</div>
								</div>
							}
						}
					</div>
				</div>
			</div>
		</div>
	</div>



@section Scripts{
	<script>
		$(document).ready(function(){
			$("#customer-tile").css({
					"background-color" : "#2c3e50",
			})
			$("#contact-tile").css({
					"background-color" : "#2c3e50",
			})

			
		})

		$("#customer-tile").click(function(){
				window.location.href = "/Customer/Index"
		})
		
</script>
}

CRMApp/Views/Shared/SupportDashboard.cshtml
@model CRMApp.ViewModels.ActivityLogViewModel;

@{
    ViewData["Title"] = "SupportDashboard";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container d-flex justify-content-center ">
	<div class="flex-column" style="width: 100%;">
		
		<div class="d-grid">
			<div class="row d-flex justify-content-between ms-0">
				<div class="col-2" style="width: 58em;margin-left:-3rem;">
					<div class="card">
						<h3 class="text-center mt-2">Overview</h3>
						<div class="card-body">
							<div class="d-grid">
								<div class="row d-inline-flex justify-content-center">

									<div class="col-sm-2" style="width: 15rem;">
										<div class="card" style="background: lightgrey;" id="customer-tile">
											<div class="card-body">
												<h4 class="text-center text-light">Total Customers </h4>
												<p class="text-center fw-bold h5 text-light">@ViewBag.CustomerCount</p>
											</div>
										</div>
									</div>
									<div class="col-sm-2" style="width: 15rem;">
										<div class="card" style="background: lightgrey;" id="contact-tile">
											<div class="card-body">
												<h4 class="text-center text-light">Total Contacts </h4>
												<p class="text-center fw-bold h5 text-light">@ViewBag.ContactCount</p>
											</div>
										</div>
									</div>

								</div>

							</div>
						</div>
					</div>
				</div>
				<div class="col-2" style="width:27em;margin-right:-2rem;">
					<div class="card shadow-sm" style="overflow-y: auto; height: 600px;">
						<h3 class="text-center mt-2">
							Activity Feed
						</h3>
						@if (Model.activityLogs.Count > 0 )
						{
							@foreach (var item in Model.activityLogs)
							{

								<div class="container mt-1 mb-1">
									<div class="card">
										<div class="card-header d-inline-flex justify-content-between">
											<span class="fw-bold">@item.ModuleId</span>
										</div>
										<div class="card-body">
											@if ((bool)item.IsDeleted)
											{
												<span class="text-danger">@item.Action  </span>  <span class="fst-italic text-end text-danger">On @Model.FormatDate(item.TimeStamp) at @item.TimeStamp.ToString("h:mm tt")</span>
											}
											else
											{
												<span class="text-success">@item.Action </span> <span class="fst-italic text-end text-success">On @Model.FormatDate(item.TimeStamp) at @item.TimeStamp.ToString("h:mm tt")</span>
											}

										</div>

									</div>
								</div>
							}

						}else
						{
							<p class="text-center fw-light mt-5">No Activity To Show</p>
						}
						
					</div>
				</div>
			</div>
		</div>
	</div>



	@section Scripts {
		<script>
			$(document).ready(function(){
				$("#customer-tile").css("background-color", "#2c3e50")
				$("#contact-tile").css({
					"background-color": "#2c3e50",
				})
			})
			$("#customer-tile").click(function () {
				window.location.href = "/Customer/Index"
			})
		</script>
	}

CRMApp/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/crm_main.css" asp-append-version="true" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbar navbar-light bg-light" style="position: fixed; top: 2rem; width: 87%; border-radius: 10px; z-index:99999;">
        <div class="container-fluid d-flex">
            <div class="navbar-brand align-items-start">
               Welcome <span class="text-black fw-bold">@await Component.InvokeAsync("User")</span>
            </div>
            <partial name="_LoginPartial" />
            
           
        </div>
    </nav>
    <div class="container mt-5 pt-4" >
        @RenderBody()
    </div>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Script.js"></script>
   <script type="text/javascript">
       $(document).ready(function() {

           var currentUrl = window.location.pathname.toLowerCase();
            $('div.nav-item div .nav-link').css('color', '#334155')
            $('div.nav-item div .nav-link').each(function() {
                var linkUrl = $(this).attr('href').toLowerCase();
                if(currentUrl == linkUrl){
                    $('div.nav-item div .nav-link').css({
                        'background-color' : '',
                        'color': '#334155'
                    })
                    
                    $(this).css({
                        'background-color': '#2c3e50',
                        'color': '#ecf0f1'
                    })
                    
                    
                }
            })
       })
   </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CRMApp/Views/Shared/_ContactForm.cshtml
@model CRMApp.ViewModels.CustomerViewModel

@if(Model == null)
{
    <p>Model is Null</p>
}
else
{
    <form id="frmContact" asp-action="SaveContact" asp-controller="Contact" method="post">
        <div asp-validation-summary="ModelOnly"></div>
        <input type="hidden" asp-for="CustomerContact.Id" />
        <input type="hidden" asp-for="CustomerContact.CustomerId" />
        <div class="modal-header">
            <h5 class="modal-title">@((Model.CustomerContact?.Id ?? 0) == 0 ? "Add Contact" : "Edit Contact")</h5>
            <a href="" class="btn btn-close"></a>
        </div>

        <div class="modal-body">

            <div class="form-group">
                <label asp-for="@Model.Customer.Name">Customer Name</label>
                <input asp-for="@Model.Customer.Name" class="form-control" value="@Model.Customer.Name" disabled />
            </div>
            <div class="form-group">
                <label asp-for="CustomerContact.ContactName">Contact Name:</label>
                <input asp-for="CustomerContact.ContactName" class="form-control" />
                <span asp-validation-for="CustomerContact.ContactName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CustomerContact.Relation">Customer Relation:</label>
                @Html.DropDownListFor(m => m.CustomerContact.Relation, Html.GetEnumSelectList<Relation>(), "--Select Relation--", new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label asp-for="CustomerContact.ContactType">Contact Type:</label>
                @Html.DropDownListFor(m => m.CustomerContact.ContactType, Html.GetEnumSelectList<CRMApp.Models.Type>(), "--Select Contact Type--", new { @class = "form-control", @id = "contactTypeList" })
            </div>

            <div class="form-group">
                <label asp-for="CustomerContact.Contact">Contact (<span id="contactType">Type</span>):</label>
                <input asp-for="CustomerContact.Contact" class="form-control" />
                <span asp-validation-for="CustomerContact.Contact" class="text-danger"></span>
            </div>
        </div>

        <div class="modal-footer">
            <a href="" class="btn btn-secondary">Cancel</a>
            <button type="button" class="btn btn-danger" id="btnSave">Save</button>
        </div>
    </form>
    
}



@section Scripts {
    <partial name="_ValidationScriptsPartial" />
  
}

CRMApp/Views/Shared/_ContactList.cshtml
@model IEnumerable<CRMApp.Models.CustomerContact>;


<div class="d-flex justify-content-center table-responsive-sm table-responsive-md">
	@if (Model.Count() == 0)
	{
		<h4 class="text-center mb-3">No Contact Found</h4>
	}
	else
	{
		<table class="table table-hover table-bordered table-striped mt-4 " style="width:98%;">
			<thead>
				<tr>
					<th>
						@Html.DisplayNameFor(model => model.ContactName)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.Relation)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.ContactType)
					</th>
					<th>
						@Html.DisplayNameFor(model => model.Contact)
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				@foreach (var item in Model)
				{
					<tr>
						<td>
							@Html.DisplayFor(modelItem => item.ContactName)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Relation)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.ContactType)
						</td>
						<td>
							@Html.DisplayFor(modelItem => item.Contact)
						</td>

						<td>
							<div class="d-flex justify-content-center gap-1">
								@if (User.IsInRole("admin") || User.IsInRole("salesrep"))
								{
									<form method="post">
										<input type="hidden" name="selectedContactId" value=@item.Id />
										<button type="submit" data-bs-toggle="modal" data-bs-target="#EditModal" class="btn btn-outline-success">Edit</button>
									</form>

								}

								@if (User.IsInRole("admin"))
								{
									<form method="post">
										<input type="hidden" name="deleteContactId" value=@item.Id />
										<button type="submit" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" class="btn btn-outline-danger">Delete</button>
									</form>
								}
							</div>

						</td>
					</tr>
				}
			</tbody>
		</table>

	}

</div>

CRMApp/Views/Shared/_NoteForm.cshtml
@model CRMApp.ViewModels.CustomerViewModel;

<form id="frmNote" asp-action="SaveNote" asp-controller="Note" method="post">
	<div asp-validation-summary="ModelOnly"></div>
	<input type="hidden" asp-for="Note.Id"/>
	<input type="hidden" asp-for="Note.CustomerId"/>
	<input type="hidden" asp-for="Note.CreatedBy" />
	<input type="hidden" asp-for="Note.CreatedAt" />
	<div class="modal-header">
		<h5 class="modal-title">@((Model.Note?.Id ?? 0) == 0 ? "Add Note" : "Edit Note")</h5>
		<a href="" class="btn btn-close"></a>
	</div>

	<div class="modal-body">
		<div class="form-group">
			<label asp-for="Note.Description">Description</label>
			<textarea asp-for="Note.Description" class="form-control"></textarea>
			<span asp-validation-for="Note.Description" class="text-danger"></span>
		</div>
		<div class="mb-3 text-success" style="font-size: 0.85em; margin-top:-15px; padding:0;">By: @Model.CurrentUsername On @Model.FormatDate(DateTime.Now) at @DateTime.Now.ToString("hh:mm tt")</div>
	</div>
	
	
	
	
		<div class="modal-footer">
			<a href="" class="btn btn-secondary">Cancel</a>
			<button type="button" class="btn btn-danger" id="btnNoteSave">Save</button>
		</div>
</form>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}